services:
  s3:
    image: quay.io/minio/minio
    command: minio server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - s3:/data
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

volumes:
  s3:
    name: s3